### ISSUE TITLE
CLI module list error

### ISSUE THREAD

**Issue by ZhouYanzhao** [ZhouYanzhao/Nest#1]
Originally reported by @doudoubilly.

Execute " nest module list --filter prm" and get the following result.(Ubuntu16)

(pt-py3) root@ebe535e9a1a8:~# nest module list --filter prm
Traceback (most recent call last):
File "/root/Envs/pt-py3/lib/python3.5/site-packages/nest/modules.py", line 346, in _import_nest_modules_from_file
spec.loader.exec_module(py_module)
File "", line 665, in exec_module
File "", line 222, in _call_with_frames_removed
File "/root/PRM/install/prm.py", line 30, in 
filter_type: Union[str, int, float] = 'median') -> nn.Module:
File "/root/Envs/pt-py3/lib/python3.5/site-packages/nest/modules.py", line 262, in _register
return create_module(args[0])
File "/root/Envs/pt-py3/lib/python3.5/site-packages/nest/modules.py", line 259, in create_module
return type('NestModule', (NestModule,), dict(slots=(), doc=doc))(func, nest_meta)
File "/root/Envs/pt-py3/lib/python3.5/site-packages/nest/modules.py", line 69, in init
self._check_definition()
File "/root/Envs/pt-py3/lib/python3.5/site-packages/nest/modules.py", line 80, in _check_definition
if v.default is not inspect.Parameter.empty and not U.is_annotation_matched(v.default, v.annotation):
File "/root/Envs/pt-py3/lib/python3.5/site-packages/nest/logger.py", line 59, in wrapper
res = func(*args, **kwargs)
File "/root/Envs/pt-py3/lib/python3.5/site-packages/nest/utils.py", line 236, in is_annotation_matched
sub_annotation = annotation.args
AttributeError: type object 'Union' has no attribute 'args'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/root/Envs/pt-py3/bin/nest", line 11, in 
sys.exit(main())
File "/root/Envs/pt-py3/lib/python3.5/site-packages/nest/main.py", line 4, in main
CLI()
File "/root/Envs/pt-py3/lib/python3.5/site-packages/nest/cli.py", line 71, in init
getattr(self, 'cmd_' + args.command)('nest ' + args.command, sys.argv[2:])
File "/root/Envs/pt-py3/lib/python3.5/site-packages/nest/cli.py", line 162, in cmd_module
module_info = ['%s (%s)' % (k, v.meta.get('version', 'version')) for k, v in module_manager]
File "/root/Envs/pt-py3/lib/python3.5/site-packages/nest/modules.py", line 702, in iter
self._update_modules()
File "/root/Envs/pt-py3/lib/python3.5/site-packages/nest/modules.py", line 692, in _update_modules
ModuleManager._import_nest_modules_from_dir(meta['module_path'], namespace, self.py_modules, self.nest_modules, meta)
File "/root/Envs/pt-py3/lib/python3.5/site-packages/nest/modules.py", line 407, in _import_nest_modules_from_dir
ModuleManager._import_nest_modules_from_file(file_path, namespace, py_modules, nest_modules, meta)
File "/root/Envs/pt-py3/lib/python3.5/site-packages/nest/modules.py", line 356, in _import_nest_modules_from_file
if (type(exc_info) is ModuleNotFoundError or type(exc_info) is ImportError) and exc_info.name is not None:
NameError: name 'ModuleNotFoundError' is not defined

**Comment by ZhouYanzhao** [comment]
Hi @doudoubilly
Could you provide your python version? 
`$ python --version`

**Comment by billqxg** [comment]
Thanks for  replying. @ZhouYanzhao 
My python version is 3.5.2. 
Pytorch version is 0.4.0.
System version is Ubutntu 16.04.

**Comment by ZhouYanzhao** [comment]
Hi @doudoubilly ,
I have pushed some updates, please try reinstalling the online version (0.1.1) with **python>=3.5.4**
```bash
$ pip install git+https://github.com/ZhouYanzhao/Nest.git --upgrade
```

**Comment by billqxg** [comment]
@ZhouYanzhao. As you suggest, I change to use python3.6.5.
After installing nest 0.1.1, I run "nest module install github@ZhouYanzhao/PRM:pytorch prm" to install PRM.
and get a result below:

(pt-py36) root@ebe535e9a1a8:~# nest module install github@ZhouYanzhao/PRM:pytorch prm
Traceback (most recent call last):
  File "/root/Envs/pt-py36/bin/nest", line 7, in <module>
    from nest.__main__ import main
  File "/root/Envs/pt-py36/lib/python3.6/site-packages/nest/__init__.py", line 1, in <module>
    from nest.parser import run_tasks
  File "/root/Envs/pt-py36/lib/python3.6/site-packages/nest/parser.py", line 8, in <module>
    from nest.modules import module_manager
  File "/root/Envs/pt-py36/lib/python3.6/site-packages/nest/modules.py", line 835, in <module>
    module_manager = ModuleManager()
  File "/root/Envs/pt-py36/lib/python3.6/site-packages/nest/modules.py", line 208, in __init__
    self._add_module_finder()
  File "/root/Envs/pt-py36/lib/python3.6/site-packages/nest/modules.py", line 638, in _add_module_finder
    class NamespaceLoader(importlib.abc.Loader):
AttributeError: module 'importlib' has no attribute 'abc'

**Comment by ZhouYanzhao** [comment]
Hi @doudoubilly 
It should be fixed by https://github.com/ZhouYanzhao/Nest/commit/7279dc1159e566f85a39bbf6c53fb369475bc63c. Please rerun `$ pip install git+https://github.com/ZhouYanzhao/Nest.git --upgrade`

**Comment by billqxg** [comment]
Hello @ZhouYanzhao  
It seems OK to install nest.while another bug occur to me.
I install  PRM by running "nest module install github@ZhouYanzhao/PRM:pytorch prm" and then I run "nest module list --filter prm" and get the result:
No available Nest modules found. You can install build-in PyTorch modules by executing "nest module install github@ZhouYanzhao/Nest:pytorch"

Then I try to run man.ipynb in PRM, bug get:
maximum recursion depth exceeded while calling a Python object. The package "main" under namespace "main" could not be imported. 
'Could not find a Nest module matches query "*fc_resnet50".'. The package "main" under namespace "main" could not be imported.

**Comment by ZhouYanzhao** [comment]
@doudoubilly 
I see. I have something to deal with for the time being. But don't worry, tomorrow I will write a bash script to help you pinpoint this bug.

**Comment by billqxg** [comment]
@ZhouYanzhao 
That' OK. Thanks for your help and your work. They inspire me a lot.

**Comment by ZhouYanzhao** [comment]
@doudoubilly 
Please download [env.yml](https://gist.githubusercontent.com/ZhouYanzhao/8dc13a7bca6120336c449f83d228d170/raw/19532cf1c5580b8e5dbdf7836c498e505b325b67/env.yml) to your home folder and run:
```bash
$ cd ~
# Make sure you have conda installed
$ conda env create -f env.yml
# Activate the environment
$ source activate prm
# Install build-in modules
$ nest module install github@ZhouYanzhao/Nest:pytorch pytorch
# Verification
$ nest module list
# Install PRM modules
$ nest module install github@ZhouYanzhao/PRM:pytorch prm
# Verify again
$ nest module list -f prm
```

**Comment by billqxg** [comment]
@ZhouYanzhao  I follow your suggestion but prm module still can  not be found.

(prm) root@ebe535e9a1a8:~# nest module install github@ZhouYanzhao/Nest:pytorch pytorch
Install "github@ZhouYanzhao/Nest:pytorch" --> "./". Continue? (Y/n)y
Cloning into 'Nest-pytorch'...
remote: Counting objects: 59, done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 59 (delta 17), reused 43 (delta 10), pack-reused 0
Unpacking objects: 100% (59/59), done.
Checking connectivity... done.
"/root/Nest-pytorch" is already installed under the namespace "nest_pytorch".
(prm) root@ebe535e9a1a8:~# nest module list
22 Nest modules found.
[0] nest_pytorch.adadelta_optimizer (0.1.0)
[1] nest_pytorch.checkpoint (0.1.0)
[2] nest_pytorch.cross_entropy_loss (0.1.0)
[3] nest_pytorch.fetch_data (0.1.0)
[4] nest_pytorch.finetune (0.1.0)
[5] nest_pytorch.image_transform (0.1.0)
[6] nest_pytorch.interval (0.1.0)
[7] nest_pytorch.lenet5 (0.1.0)
[8] nest_pytorch.loss_meter (0.1.0)
[9] nest_pytorch.mnist (0.1.0)
[10] nest_pytorch.multilabel_soft_margin_loss (0.1.0)
[11] nest_pytorch.network_trainer (0.1.0)
[12] nest_pytorch.pascal_voc_classification (0.1.0)
[13] nest_pytorch.pascal_voc_object_categories (0.1.0)
[14] nest_pytorch.print_state (0.1.0)
[15] nest_pytorch.rle_decode (0.1.0)
[16] nest_pytorch.rle_encode (0.1.0)
[17] nest_pytorch.sgd_optimizer (0.1.0)
[18] nest_pytorch.topk_meter (0.1.0)
[19] nest_pytorch.torchvision_model (0.1.0)
[20] nest_pytorch.update_lr (0.1.0)
[21] nest_pytorch.vis_trend (0.1.0)
(prm) root@ebe535e9a1a8:~# nest module install github@ZhouYanzhao/PRM:pytorch prm
Install "github@ZhouYanzhao/PRM:pytorch" --> "./". Continue? (Y/n)y
Cloning into 'PRM-pytorch'...
remote: Counting objects: 56, done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 56 (delta 4), reused 34 (delta 0), pack-reused 12
Unpacking objects: 100% (56/56), done.
Checking connectivity... done.
Namespace "prm" is already bound to the path "/root/PRM".
(prm) root@ebe535e9a1a8:~# nest module list -f prm
No available Nest modules found. You can install build-in PyTorch modules by executing "nest module install github@ZhouYanzhao/Nest:pytorch".

**Comment by ZhouYanzhao** [comment]
@doudoubilly 
The installation is failed due to `Namespace "prm" is already bound to the path "/root/PRM".`
Try:
```bash
# Remove old installation
$ nest module remove prm -d -y
# Install again
$ nest module install github@ZhouYanzhao/PRM:pytorch prm
# Check the content is properly downloaded
$ ls ./PRM-pytorch
# Check the path is properly added
$ nest setting show
# Check modules
$ nest module check
# List all modules
$ nest module list
```
And check the [shell recording](https://asciinema.org/a/7Mt3LA5DtaHTz6bPoxYbh0v7d) for expected output.

**Comment by billqxg** [comment]
@ZhouYanzhao I finally get through it. Thank you very much!

**Comment by ZhouYanzhao** [comment]
My pleasure.
