### ISSUE TITLE
RuntimeError: Unable to load global settings of Nest. load() missing 1 required positional argument: 'Loader'

### ISSUE THREAD

**Issue by SteamerLee** [ZhouYanzhao/Nest#4]
Hi, I just downloaded the Nest and S3N and try to get it run. When importing the nest module, an error shown as title occurs. Any idea can solve this problem? Many thanks!

Input:
from nest import register

Output:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nest/settings.py", line 126, in <module>
    settings = SettingManager()
  File "/usr/local/lib/python3.6/dist-packages/nest/settings.py", line 107, in __init__
    self.load()
  File "/usr/local/lib/python3.6/dist-packages/nest/settings.py", line 119, in load
    self.settings, self.user_settings = SettingManager.load_settings()
  File "/usr/local/lib/python3.6/dist-packages/nest/settings.py", line 93, in load_settings
    settings = yaml.load(DEFAULT_SETTINGS)
TypeError: load() missing 1 required positional argument: 'Loader'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/nest/__init__.py", line 1, in <module>
    from nest.parser import run_tasks
  File "/usr/local/lib/python3.6/dist-packages/nest/parser.py", line 7, in <module>
    import nest.utils as U
  File "/usr/local/lib/python3.6/dist-packages/nest/utils.py", line 12, in <module>
    from nest.logger import exception
  File "/usr/local/lib/python3.6/dist-packages/nest/logger.py", line 7, in <module>
    from nest.settings import settings
  File "/usr/local/lib/python3.6/dist-packages/nest/settings.py", line 128, in <module>
    raise RuntimeError('Unable to load global settings of Nest. %s' % exc_info)
RuntimeError: Unable to load global settings of Nest. load() missing 1 required positional argument: 'Loader'

Platform: Ubuntu 20.04
Python 3.6

**Comment by SteamerLee** [comment]
It may be caused by the version of YAML. It works after adding "Loader=yaml.Loader" in yaml.load (i.e., yaml.load(xxx, Loader=yaml.Loader)) . Thanks!
